persistence:
  enabled: false

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m

service:
  type: NodePort
  nodePort: 32000

adminPassword: admin123

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        access: proxy

      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy

      - name: Jaeger
        type: jaeger
        url: http://jaeger.observability.svc.cluster.local:16686
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: istio
        folder: Istio
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/istio

dashboards:
  istio:
    istio-mesh:
      gnetId: 7639
      revision: 1
      datasource: Prometheus
    istio-service:
      gnetId: 7636
      revision: 1
      datasource: Prometheus
    istio-workload:
      gnetId: 7630
      revision: 1
      datasource: Prometheus
    k8s-cluster:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
