auth:
  strategy: anonymous

deployment:
  service_type: NodePort

server:
  port: 20001

external_services:
  prometheus:
    url: "http://prometheus-server.monitoring.svc.cluster.local"

  grafana:
    enabled: true
    in_cluster_url: "http://grafana.monitoring.svc.cluster.local:80"
    url: "http://10.0.2.15:32000"

  tracing:
    enabled: true
    in_cluster_url: "http://jaeger.observability.svc.cluster.local:16686"
    use_grpc: false
    provider: jaeger
