mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s
  tag: latest

config:

  receivers:

    filelog:
      include:
        - /var/log/pods/*/*/*.log

      exclude:
        - /var/log/pods/*/otel-collector*/*.log

      start_at: beginning

      include_file_path: true
      include_file_name: false

      operators:

        - type: router
          id: get-format
          routes:
            - expr: 'body matches "^\\{"'
              output: parser-docker

            - expr: 'body matches "^[^ Z]+ "'
              output: parser-crio


        - type: json_parser
          id: parser-docker
          output: extract_metadata_from_filepath

          timestamp:
            parse_from: attributes.time
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'


        - type: regex_parser
          id: parser-crio
          output: extract_metadata_from_filepath

          regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'


        - type: move
          id: extract_metadata_from_filepath
          from: attributes["log.file.path"]
          to: resource["filepath"]
  exporters:

    otlphttp/loki:
      endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
      tls:
        insecure: true

    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true


  extensions:

    health_check:
      endpoint: ${env:MY_POD_IP}:13133


  processors:

    memory_limiter:
      check_interval: 1s
      limit_mib: 400

    batch: {}

    k8s_attributes:
      auth_type: serviceAccount
      passthrough: false

      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.deployment.name
          - k8s.node.name

      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.ip
        - sources:
            - from: connection 


  service:

    extensions:
      - health_check

    pipelines:

      logs:
        receivers:
          - filelog

        processors:
          - memory_limiter
          - k8s_attributes
          - batch

        exporters:
          - otlphttp/loki
