mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.104.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    protocol: TCP
  metrics:
    enabled: false
    containerPort: 8888
    servicePort: 8888

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411

  processors:
    batch:
      timeout: 5s
      send_batch_size: 512
    memory_limiter:
      check_interval: 1s
      limit_mib: 200
      spike_limit_mib: 50
    resource:
      attributes:
        - key: cluster
          value: "k3s-stage"
          action: upsert

  exporters:
    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true
    otlp/jaeger:
      endpoint: "jaeger.observability.svc.cluster.local:4317"
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"
      tls:
        insecure: true
    otlphttp/loki:
      endpoint: "http://loki.monitoring.svc.cluster.local:3100/otlp"
      tls:
        insecure: true
    debug:
      verbosity: basic

  service:
    pipelines:
      traces:
        receivers: [otlp, zipkin]
        processors: [memory_limiter, batch, resource]
        exporters: [otlp/jaeger,otlp/tempo]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch, resource]
        exporters: [prometheusremotewrite]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch, resource]
        exporters: [otlphttp/loki]
