config:
  exporters:
    debug:
      verbosity: basic
    otlp/jaeger:
      endpoint: jaeger.observability.svc.cluster.local:4317
      tls:
        insecure: true
    otlphttp/loki:
      endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
      tls:
        insecure: true
  processors:
    batch:
      send_batch_size: 512
      timeout: 5s
    memory_limiter:
      check_interval: 1s
      limit_mib: 200
      spike_limit_mib: 50
    resource:
      attributes:
      - action: upsert
        key: cluster
        value: k3s-stage
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411
  service:
    telemetry:
      metrics:
        address: ":8889" 
    pipelines:
      logs:
        exporters:
        - otlphttp/loki
        processors:
        - memory_limiter
        - batch
        - resource
        receivers:
        - otlp
      metrics:
        exporters:
        - prometheusremotewrite
        processors:
        - memory_limiter
        - batch
        - resource
        receivers:
        - otlp
      traces:
        exporters:
        - otlp/jaeger
        processors:
        - memory_limiter
        - batch
        - resource
        receivers:
        - otlp
        - zipkin
image:
  pullPolicy: IfNotPresent
  repository: otel/opentelemetry-collector-contrib
  tag: 0.104.0
mode: deployment
ports:
  metrics:
    containerPort: 8888
    enabled: false
    servicePort: 8888
  otlp:
    containerPort: 4317
    enabled: true
    protocol: TCP
    servicePort: 4317
  otlp-http:
    containerPort: 4318
    enabled: true
    protocol: TCP
    servicePort: 4318
  zipkin:
    containerPort: 9411
    enabled: true
    protocol: TCP
    servicePort: 9411
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
