USER-SUPPLIED VALUES:
additionalEnvVars:
- name: GEMINI_API_KEY
  valueFrom:
    secretKeyRef:
      key: GEMINI_API_KEY
      name: holmes-llm
- name: TOOL_SCHEMA_NO_PARAM_OBJECT_IF_NO_PARAMS
  value: "true"
config:
  model: gemini-flash
modelList:
  gemini-flash:
    api_key: '{{ env.GEMINI_API_KEY }}'
    model: gemini/gemini-flash-lite-latest
    temperature: 0
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
toolsets:
  kubernetes/core:
    enabled: true
  kubernetes/logs:
    enabled: true
  prometheus/metrics:
    config:
      discover_metrics_from_last_hours: 1
      prometheus_url: http://obs-prometheus-server.monitoring.svc.cluster.local:80
      query_timeout_seconds_default: 20
      tool_calls_return_data: true
    enabled: true
    subtype: prometheus
