apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  namespace: online-boutique
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: shippingservice
      containers:
        - name: server
          image: yosrtaktak/shippingservice:v1@sha256:dcdf378d3a5b162c2a92ac349eebcfa8e946666a2f0f311a7dfa86f1aeaa16eb
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
          resources:
            requests:
              cpu: 100m
              memory: 4Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: online-boutique
spec:
  selector:
    app: shippingservice
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
