mongodb:
  architecture: replicaset
  replicaCount: 1
  arbiter:
    enabled: false
  auth:
    enabled: true
    rootUser: "root"
    existingSecret: "litmus-mongodb"
  persistence:
    enabled: true
