persistence:
  enabled: false

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m

service:
  type: NodePort
  nodePort: 32000

adminPassword: admin123

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        access: proxy
        uid: prometheus
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        uid: loki
      - name: Jaeger
        type: jaeger
        url: http://jaeger.observability.svc.cluster.local:16686
        access: proxy
        uid: jaeger

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: istio
        folder: Istio
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/istio

dashboards:
  istio:
    istio-mesh:
      gnetId: 7639
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    istio-service:
      gnetId: 7636
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    istio-workload:
      gnetId: 7630
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    k8s-cluster:
      gnetId: 6417
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

grafana.ini:
  panels:
    disable_sanitize_html: true
  unified_alerting:
    enabled: false

env:
  GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/istio/istio-mesh.json
