apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
      tracing:
        zipkin:
          address: otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:9411
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    enableTracing: true
    traceSampling: 100.0
    rootNamespace: istio-system
    serviceScopeConfigs:
    - scope: GLOBAL
      servicesSelector:
        matchExpressions:
        - key: istio.io/global
          operator: In
          values:
          - "true"
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: otel-collector.monitoring.svc.cluster.local

    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mesh":"defaultConfig:\n  discoveryAddress: istiod.istio-system.svc:15012\n  image:\n    imageType: distroless\n  proxyMetadata:\n    ISTIO_META_ENABLE_HBONE: \"true\"\n  tracing:\n    zipkin:\n      address: otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:9411\ndefaultProviders:\n  metrics:\n  - prometheus\nenablePrometheusMerge: true\nenableTracing: true\ntraceSampling: 100.0\nrootNamespace: istio-system\nserviceScopeConfigs:\n- scope: GLOBAL\n  servicesSelector:\n    matchExpressions:\n    - key: istio.io/global\n      operator: In\n      values:\n      - \"true\"\ntrustDomain: cluster.local","meshNetworks":"networks: {}"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-06-30T09:29:08Z","labels":{"app.kubernetes.io/instance":"istio","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"istiod","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"1.30.2","helm.sh/chart":"istiod-1.30.2","install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.30.2","release":"istio"},"name":"istio","namespace":"istio-system","resourceVersion":"35478","uid":"0ff875fa-fc2e-4859-96e6-b91816b45167"}}
  creationTimestamp: "2026-06-30T09:29:08Z"
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.30.2
    helm.sh/chart: istiod-1.30.2
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.30.2
    release: istio
  name: istio
  namespace: istio-system
  resourceVersion: "151203"
  uid: 0ff875fa-fc2e-4859-96e6-b91816b45167
