apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - peerauthentication.yaml
  - authorizationpolicies.yaml
  - gateway.yaml
  - virtualservice-internal.yaml
  - serviceentry-egress.yaml
  - telemetry.yaml
