apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-request-operation
  namespace: online-boutique
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_DURATION
      tagOverrides:
        request_operation:
          value: "request.url_path"
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        request_operation:
          value: "request.url_path"
