set -e
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<EOSQL
CREATE USER goalert PASSWORD '$GOALERT_DB_PASSWORD';
CREATE DATABASE goalert OWNER goalert;
CREATE USER incident PASSWORD '$INCIDENT_DB_PASSWORD';
CREATE DATABASE incident_db OWNER incident;
EOSQL
