apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
  namespace: online-boutique
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: loadgenerator
      containers:
        - name: main
          image: yosrtaktak/loadgenerator:v1
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "10"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

