apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: online-boutique
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      containers:
        - name: server
          image: yosrtaktak/adservice:v1
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            grpc:
              port: 9555
          livenessProbe:
            grpc:
              port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: online-boutique
spec:
  selector:
    app: adservice
  ports:
    - port: 9555
      targetPort: 9555
      name: grpc

