apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-rag
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yosrtaktak/stage-sre-plateforme
    targetRevision: stage-yosr
    path: manifests/sre-agent/rag
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
