apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-annotator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-annotator-reader
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-annotator-reader-binding
subjects:
  - kind: ServiceAccount
    name: deploy-annotator
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: deploy-annotator-reader
  apiGroup: rbac.authorization.k8s.io
