apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: online-boutique
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      containers:
        - name: server
          image: yosrtaktak/adservice:v1@sha256:ddf4813cc78fcb86d6e11268cca597bd380d524a0de6b15a0d30f9bdfcb1a319
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            grpc:
              port: 9555
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            grpc:
              port: 9555
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: online-boutique
spec:
  selector:
    app: adservice
  ports:
    - port: 9555
      targetPort: 9555
      name: grpc

