apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - namespace.yaml
  - ../istio
  - redis-cart/deployment.yaml
  - productcatalogservice/deployment.yaml
  - currencyservice/deployment.yaml
  - paymentservice/deployment.yaml
  - shippingservice/deployment.yaml
  - emailservice/deployment.yaml
  - adservice/deployment.yaml
  - recommendationservice/deployment.yaml
  - cartservice/deployment.yaml
  - checkoutservice/deployment.yaml
  - frontend/deployment.yaml
  - loadgenerator/deployment.yaml
