apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: online-boutique
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: currencyservice
      containers:
        - name: server
          image: yosrtaktak/currencyservice:v1@sha256:8bab98f6dcbdd8e45dcf264db58c0f673eabab2c2c301ce1163d646069fef14f
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            grpc:
              port: 7000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            grpc:
              port: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: online-boutique
spec:
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 7000
      name: grpc
